# файл конфигурации клиента

env: local                    # окружение (local, dev, prod)
serverAddress: 127.0.0.1:9090 # адрес:порт на которых работает сервер

# секретный ключ шифрования, которым вместе с паролем пользователя шифруем передаваемые приватные данные
# дополняем строку пароля до 32х байтной длины
secretKey: Secret
