# файл конфигурации клиента

# окружение (local, dev, prod)
env: local
# адрес:порт на которых работает сервер
serverAddress: localhost:9090

# секретный ключ шифрования, которым вместе с паролем пользователя шифруем передаваемые приватные данные
# дополняем строку пароля до 32х байтной длины
secretKey: Secret
